import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored chart source from the @bklit shadcn registry. Regenerated by
    // `npx shadcn@latest add @bklit/*`, so hand-fixing lint here would be
    // overwritten. TypeScript still type-checks these files.
    "src/components/charts/**",
  ]),
  {
    /*
     * Plate's editor source, vendored in by `npx shadcn@latest add @plate/*`.
     *
     * A targeted override rather than a global ignore, deliberately. These
     * files get regenerated by the CLI, so hand-fixing their `any`s is work
     * that gets overwritten on the next upgrade — but we DO edit some of them
     * (mention-node reads real CRM records now), and the hook rules that have
     * caught real bugs in this codebase should keep applying. So: this one
     * rule off, everything else on.
     */
    files: [
      "src/components/shadcn/**/*.{ts,tsx}",
      "src/components/editor/**/*.{ts,tsx}",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      /*
       * Plate returns render functions from factories (block-list,
       * block-draggable). They're never referenced by name, so a displayName
       * buys nothing but a slightly nicer React DevTools tree — and adding one
       * to a generated file gets overwritten on the next `shadcn add`.
       */
      "react/display-name": "off",
    },
  },
]);

export default eslintConfig;
